// <auto-generated />
using System;
using Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Core.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Core.Entities.DeviceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Idiom");

                    b.Property<string>("Imei")
                        .HasMaxLength(24);

                    b.Property<string>("Manufacturer");

                    b.Property<string>("Model");

                    b.Property<string>("Name");

                    b.Property<string>("Platform");

                    b.Property<int>("Status");

                    b.Property<string>("Version");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Core.Entities.DeviceLastLocationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Accuracy");

                    b.Property<double>("Altitude");

                    b.Property<string>("Code");

                    b.Property<long?>("DeviceEntity_Id");

                    b.Property<double>("Direction");

                    b.Property<bool>("IsFromMockProvider");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name");

                    b.Property<double>("Speed");

                    b.Property<DateTimeOffset>("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("DeviceEntity_Id");

                    b.ToTable("DeviceLastLocations");
                });

            modelBuilder.Entity("Core.Entities.DeviceLocationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Accuracy");

                    b.Property<double>("Altitude");

                    b.Property<string>("Code");

                    b.Property<long?>("DeviceEntity_Id");

                    b.Property<double>("Direction");

                    b.Property<bool>("IsFromMockProvider");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name");

                    b.Property<double>("Speed");

                    b.Property<DateTimeOffset>("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("DeviceEntity_Id");

                    b.ToTable("DeviceLocations");
                });

            modelBuilder.Entity("Core.Entities.DeviceLastLocationEntity", b =>
                {
                    b.HasOne("Core.Entities.DeviceEntity", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceEntity_Id");
                });

            modelBuilder.Entity("Core.Entities.DeviceLocationEntity", b =>
                {
                    b.HasOne("Core.Entities.DeviceEntity", "Device")
                        .WithMany("Locations")
                        .HasForeignKey("DeviceEntity_Id");
                });
#pragma warning restore 612, 618
        }
    }
}
